name : 'Commit Message Check'

on :
  pull_request :
    types :
      - opened
      - edited
      - reopened
      - synchronize
  push :
    branches :
      - "dev"
      - "wip"
      - "feature/*"
      - "bugfix/*"
      - "improvement/*"
      - "library/*"
      - "prerelease/*"
      - "hotfix/*"
      - "*.*.x"
jobs :
  check-commit-message :
    name : Check Commit Message
    runs-on : ubuntu-latest
    steps :
      - name : Check Commit Type
        uses : gsactions/commit-message-checker@v2
        with :
          pattern : '^(feat|fix|docs|style|refactor|perf|test|chore|build|ci)(.+?)?: .+'
          flags : 'gm'
          error : 'Your commit title did not follow semantic versioning. Please see https://github.com/IQKV/.github/blob/dev/SEMANTIC_COMMITS.md'
      - name : Check Line Length
        uses : gsactions/commit-message-checker@v2
        with :
          pattern : '^.{6,220}$'
          error : 'The maximum line length of 220 characters is exceeded.'
          excludeDescription : 'true' # this excludes the description body of a pull request
          excludeTitle : 'false'
          checkAllCommitMessages : 'false'
          accessToken : ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
